### PR TITLE
Add documentation to the lockable-resources-plugin APIs and help files

### PR DESCRIPTION
**Pull request by darius-m**
This work adds documentation for the internal APIs and help files for the fields in the Jenkins interface.
Fixed some errors that were in the older pull request.

### CODE REVIEW

**Comment by darius-m** [comment]
Added sign-offs in the commit messages. Feedback is appreciated.

**Comment by eddyp** [comment]
Added issue https://issues.jenkins-ci.org/browse/JENKINS-30015 in Jira.

**Comment by TobiX** [comment]
Unfortunately, this is very old and conflicts with the current code base... Closing for now

**Comment by eddyp** [comment]
Go figure...

**Pull request closed without merging**
