### PR TITLE
Create implicit locks as ephemeral

### PR DESCRIPTION
**Pull request by bozaro**
Motivation: I want to use the commit identifier in the lock, but do not kill Jenkins with garbage locks.

The basic idea: automatically remove locks if they were not explicitly declared in the config.

Changes:
- If lock was not created manually by `Configure System`, it became ephemeral and would removed after free (`isEphemeral` flag are preset in `Lockable Resources` page);
- Ephemeral locks is not present in `Manage Jenkins` > `Configure System` page;
- Ephemeral locks became non-ephemeral on declaring lock in `Configure System` page;
- Non-ephemeral locks became ephemeral on delete locked resource from `Configure System` page.

Also I found a minor bug on autocreation lock resources from `Free Style` jobs (see: #139).

### CODE REVIEW

**Comment by bozaro** [comment]
Rebased to master for resolve merge conflicts

**Comment by bozaro** [comment]
Rebase without reformat code for reduce diff size.

**Comment by stuartrowe** [comment]
@TobiX any chance this will get released soon?

**Comment by darxriggs** [comment]
@bozaro Can you please have a look at this change again: With this change (included in plugin v2.6) its not anymore possible to remove the last lockable resource in the global Jenkins configuration.

**Comment by bozaro** [comment]
@darxriggs 
I built this plugin from revision 7eaf7cc2b3f8848a71262fce373b873ed6ae90a4 and can't reproduce you issue. But on latest 2.7 it's reproduced very simple...

**Comment by darxriggs** [comment]
Sorry for the inconvenience. After some more investigation the culprit seems to be 417c1a0be64a63b38a2283bc30cbeb33393aad76.

**Pull request merged**
