### PR TITLE
Eliminate multiplicate code in LockableResourcesRootAction

### PR DESCRIPTION
**Pull request by mPokornyETM**
One of multiple refactoring PRs.
This one will eliminate multiplicated code in LockableResourcesRootAction and also prepare it to improve the API to handle with multiple resources in one request.

### Testing done

Provide some manual tests. Automatic tests are OK (at my local node) I do not provide new automatic tests, because the lines shall be covered by 'legacy' tests as well.

### Proposed upgrade guidelines

N/A

### Localizations

N/A

### Submitter checklist

- ~~[ ] The Jira / Github issue, if it exists, is well-described.~~
  There is no extra issue for this changes
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - The changelog generator for plugins uses the **pull request title as the changelog entry**.
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during the upgrade.
- [x] There is automated testing or an explanation that explains why this change has no tests.
- [x] New public functions for internal use only are annotated with `@NoExternalUse`. In case it is used by non java code the `Used by {@code <panel>.jelly}` Javadocs are annotated.

- ~~[ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease the future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).~~
- ~~[ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.~~
- ~~[ ] For new APIs and extension points, there is a link to at least one consumer.~~
- ~~[ ] Any localizations are transferred to *.properties files.~~
- ~~[ ] Changes in the interface are documented also as [examples](src/doc/examples/readme.md).~~

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There is at least one (1) approval for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the **pull request title** and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically. See also [release-drafter-labels](https://github.com/jenkinsci/.github/blob/ce466227c534c42820a597cb8e9cac2f2334920a/.github/release-drafter.yml#L9-L50).
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] java code changes are tested by automated test.

### CODE REVIEW

**Comment by mPokornyETM** [comment]
@g3n35i5 or @mark-reiche maybe you can review this changes

**Review by g3n35i5 — APPROVED** [review]
I looked at the changes, looks good to me. However, I have not tested the code locally. One note: Would it possibly be more elegant to have method `getResourcesFromRequest` throw an exception and wrap the entire calling function in a try/catch? Then you would save a lot of `resource == null` checks and returns.

**Comment by mark-reiche** [comment]
I have not finished reviewing it (and right now I have no access to github). I noticed in the getResources-method you added, that you spelled 'todo' in lower letters in the comment. I'd suggest spelling it 'TODO' (all caps, because otherwise it might not be caught by Task Scanner).


Am 29. Januar 2023 14:00:08 MEZ schrieb Martin Pokorny ***@***.***>:
>@g3n35i5 or @mark-reiche maybe you can review this changes
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jenkinsci/lockable-resources-plugin/pull/451#issuecomment-1407657209
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mPokornyETM** [comment]
> I looked at the changes, looks good to me. However, I have not tested the code locally. One note: Would it possibly be more elegant to have method `getResourcesFromRequest` throw an exception and wrap the entire calling function in a try/catch? Then you would save a lot of `resource == null` checks and returns.

thx. That shall works. The function is private and it shall provide no side effects. I will try it.

**Comment by mPokornyETM** [comment]
> @g3n35i5 or @mark-reiche maybe you can review this changes

I see, I recognize that too, that git hub does not understand your ID correctly

[@g3n35i5](https://github.com/g3n35i5) or [@mark-reiche](https://github.com/mark-reiche) Can I add you guys in to developer list in this plugin. I do the mostly job by my self and it fine for me, but I do not like PRs without review. That only one what I am missing and it will helps to me extremely.

**Comment by g3n35i5** [comment]
> [@g3n35i5](https://github.com/g3n35i5) or [@mark-reiche](https://github.com/mark-reiche) Can I add you guys in to developer list in this plugin. I do the mostly job by my self and it fine for me, but I do not like PRs without review. That only one what I am missing and it will helps to me extremely.

Sure, I'd be happy to help!

**Comment by mPokornyETM** [comment]
> > [@g3n35i5](https://github.com/g3n35i5) or [@mark-reiche](https://github.com/mark-reiche) Can I add you guys in to developer list in this plugin. I do the mostly job by my self and it fine for me, but I do not like PRs without review. That only one what I am missing and it will helps to me extremely.
> 
> Sure, I'd be happy to help!

Can you please look here and do the steps described there? I can not do it for you, because it must be done with our accounts ;-)
https://github.com/jenkins-infra/repository-permissions-updater/pull/3112

Thx

**Comment by mark-reiche** [comment]
I filed this one:
https://github.com/jenkins-infra/repository-permissions-updater/issues/3113
- hope this works as expected :)

**Pull request merged**
