### PR TITLE
Merge and add resources capabilities selection as replacement for labels

### PR DESCRIPTION
**Pull request by Epsilon-B**
Merge of pull requests #26, #32 and #38 + Capabilities selection

### CODE REVIEW

**Comment by Epsilon-B** [comment]
Merge of pull requests #26, #32 and #38 finally done
Since it is both my first plugin and git usage, it was a bit of a mess.
I have (in principle) managed the backward compabilities
And yes, I have created some new subpackages, moved and even renamed some classes: so it is more complicated for diff checks...

It should resolve [JENKINS-34273](https://issues.jenkins-ci.org/browse/JENKINS-34273) + [JENKINS-34268](https://issues.jenkins-ci.org/browse/JENKINS-34268) (see added test case and PR #26).
The new pipeline step full syntax (backward compatibility ensured):
`lock(resource: 'resource1 resource2', resources: ['resource1', 'resource2'], label: 'label1 label2', labels: ['label1', 'label2'], quantity: 2, variable: 'MY_VAR', capability: 'label1 label2', capabilities: ['label1', 'label2'])`

I have also extended the notion of "labels" to the notion of "capabilities".
Each resource can have multiple capabilities that can be selected or prohibited during lock process.
Only free style project can (currently) fully use these "capabilities", with the help of a new job parameter type "LockableResourcesParameterDefinition/Value":
- at job creation, one can define required and prohibited capabilities, and what kind of selection users can do at execution (resources names or capabilities)
- at execution, users can only select resources/capabilities that are compatible with these capabilties, based on all the existing resources

Fell free to re-use this work if it is worth (maybe a merge on the trunk ? :) )

**Comment by Epsilon-B** [comment]
By the way, I have also updated the POM reference for Jenkins 2.19.1: I don't know if it is really a nice idea for the trunk.
Moreover, FindBugs has also been activated in the POM file.

**Comment by Epsilon-B** [comment]
I have splited the old "reservation" action in 2 disctinct functionalities:
1/ the "online"/"offline" function: mostly same behavior as previously: the resource can not be use anymore (by anyone) (OFFLINE permission is now needed for the associated tasks)
2/ the new "reservation" which allow A (with the RESERVE permission) to grant B (no permission needed) an exclusive use of a resource for a limited duration: the resource is considered as "locked" for anyone but B.

Moreover, to prevent reservation hell, I have enforced the UnReserve button for A or B only (or anyone with the UNLOCK permission)
The default duration and the max duration of reservations can be configured in the Admin section of Jenkins.

It will be usefull at my work since the resources are mostly used for durability tests (> 3 days) by several teams, and giving them the rights to use the resource must have a duration limitation (and a team leader as responsible).

**Comment by Epsilon-B** [comment]
A new (optional) widget is available in main jenkins view (see Jenkins admin panel to show/hide the widget).
It contains the resources list and their status (available/queued/locked/offline/reserved).

**Comment by Epsilon-B** [comment]
Pull request replaced with PR #41

**Comment by sobczyk** [comment]
What's the status of this PR?
It would be useful to be able to pass a list of resources to lock.

**Comment by crummy** [comment]
It looks like this PR was closed for #41 which has stalled (perhaps due to such a large scope). It'd be great if we could push to get this merged, as I think this incremental progress would be easier and provide significant value to the plugin (certainly to my workflow).

**Comment by roel0** [comment]
Created a work around for this:
https://github.com/roel0/super_lock/tree/master

**Pull request closed without merging**
