### PR TITLE
Reserved timestamp (continuation of #226)

### PR DESCRIPTION
**Pull request by offa**
*See #225 and #226*.

PR merged with master and conflicts resolved.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jimklimov** [comment]
Note: seems to also add at least PR #227 as well as an "Edit note" link to comment stuff about a resource.

While there are small merge conflicts with my #144 and/or #279, they are easy to solve and the result plays together well.

So thanks, this PR became part of my "private build" branch along with other stalled features.

**Comment by basil** [comment]
@offa @jimklimov Feel free to adopt this plugin if you want to deliver these features.

**Comment by offa** [comment]
> I had a bit of a head-scratcher about commit b0b6632 above (removing .github/release-drafter.yml and .github/workflows/maven.yml) - any idea if that is needed and what the effect would be? (In other words, what is a reasonable current publishing approach? is this automation the future or the past?)

No idea, but I'm going to fix this up.

The GH Action CI build doesn't make too much sense since the Jenkins infrastructure is used … I guess …
But `release-drafter.yml` is good as it's on `master`.

So here's what I'm going to do:

- merge with `master` and fix the conflicts
- restore `.github/` to `master` state
- I'll squash / cleanup history

Let me know if there are other issues to address :+1:

**Comment by offa** [comment]
Done

**Comment by jimklimov** [comment]
Looks great, neat and tidy, thanks!

**Pull request merged**
