### PR TITLE
JENKINS-55182 / #121: add support for configuration as code

### PR DESCRIPTION
**Pull request by Bryann**
Currently without unit test due to the old jenkins 1.609.1 version.

If the jenkins version for unit-tests will be updated to 2.60.3 or newer, we can write a unit test according to  https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/REQUIREMENTS.md

### CODE REVIEW

**Comment by uhanisch** [comment]
Well done.

Writing unit test for would implied a change of many dependcies in the pom.xml
(for Jenkins version >= 2.60)
Can we go for it?
Or is a backward compatibility to Jenkins 1.x still required?

**Comment by darxriggs** [comment]
@haithir / @fbelzunc / @dcendents / @amuniz / @abayer who is really maintaining this plugin at the moment? Can someone please have a look at this pull request?

**Comment by darxriggs** [comment]
@Bryann now that #127 is merged you may go for the tests.

**Comment by TobiX** [comment]
@Bryann Friendly ping: Want to rebase & add a test?

**Comment by R3d-Dragon** [comment]
Hi @TobiX ,

i created another PR form a different github account because i locked out myself.
See https://github.com/jenkinsci/lockable-resources-plugin/pull/146 

You can delete/refuse this PR.

**Pull request closed without merging**
