### PR TITLE
Implement ephemeral lock support.

### PR DESCRIPTION
**Pull request by shantur**
If locks are set to ephemeral, they will be deleted once freed.

### CODE REVIEW

**Comment by shantur** [comment]
Anyone who wants to try this : 
[lockable-resources.hpi.zip](https://github.com/jenkinsci/lockable-resources-plugin/files/2920104/lockable-resources.hpi.zip)

**Comment by shantur** [comment]
@abayer @amuniz

**Comment by shantur** [comment]
@haithir maybe you can help

**Comment by StyleT** [comment]
@shantur  @abayer @amuniz any updated here? :) We really need this feature

**Comment by gabloe** [comment]
This support is really needed.  Any updates on this?

**Comment by darxriggs** [comment]
@shantur could you please resolve the merge conflicts?

**Comment by shantur** [comment]
@darxriggs : Done

**Comment by darxriggs** [comment]
@TobiX can you have a look at this?

**Comment by offa** [comment]
There's a related issue in the Jenkins Jira: [**JENKINS-55486**](https://issues.jenkins-ci.org/browse/JENKINS-55486)

**Comment by bozaro** [comment]
Another ephemeral locks implementation: #138

**Comment by TobiX** [comment]
Everyone interested in this: Please take a look at #138 which neatly sidesteps all the issues I have with this implementation.

**Comment by shantur** [comment]
Closing in favour of https://github.com/jenkinsci/lockable-resources-plugin/pull/138/

**Pull request closed without merging**
