### PR TITLE
[JENKINS-46494] Add guard in LockableResourcesManager that avoid locking more resources than required

### PR DESCRIPTION
**Pull request by mantonsson**
Without the check, in certain edge cases the resource manager would lock more resources than it actually require

Can be recreated using the following pipeline and trigger a bunch of them using different NUM_RESOURCES as values. 
I had 4 resources with label "xmamama" configured. 

After about 4-10 builds the error will start to appear.

```
properties([
    parameters ([
        string(name: 'NUM_RESOURCES')
    ])
]);

node {
    def askFor = params.NUM_RESOURCES as Integer
    lock(label: "xmamama", quantity: askFor) {
        def clients = org.jenkins.plugins.lockableresources.LockableResourcesManager.class.get().getResourcesFromBuild(currentBuild.getRawBuild())
        echo("Asked for ${askFor} resources, got ${clients.size()}: ${clients.toString()}")
        sleep (60 * 10)
        if (askFor != clients.size()) {
            error ("Wrong amount of resources aquired")
        }
    }
}
```

image

### CODE REVIEW

**Comment by mantonsson** [comment]
I'm not sure why the checks have failed, does anyone have a clue? 
The error seems related to org.hamcrest which i'm pretty sure i haven't touched. Anyone have any ideas?

`java.lang.NoSuchMethodError: org.hamcrest.CoreMatchers.containsString(Ljava/lang/String;)Lorg/hamcrest/Matcher;`

**Comment by mantonsson** [comment]
There was an issue with maven dependencies mockito+junit tied to a certain version which has been updated

**Comment by jimklimov** [comment]
Note to self (or someone else): start by picking the test from this PR to check if the past 5 years of plugin evolution have solved this already (notably, seems I addressed a similar-sounding issue with #279 recently)

**Comment by mPokornyETM** [comment]
It looks to be done

**Pull request closed without merging**
