### PR TITLE
Revert "New Crowdin updates" until we find why we have two sets of translated properties

### PR DESCRIPTION
**Pull request by gounthar**
Reverts jenkinsci/lockable-resources-plugin#369

### CODE REVIEW

**Comment by gounthar** [comment]
Ok, thank you.

**Review by mPokornyETM — APPROVED** [review]
Ok, please revert this changes, It looks it was added by crowdin action. I thing we shall check our crowdin config again.

Original (and correct one) is:
src\main\resources\**org**\jenkins\plugins\lockableresources\Messages.properties

And crowdin add it new translations into:
src\main\resources\**io**\jenkins\plugins\lockableresources

which is definitive wrong.

**Comment by mPokornyETM** [comment]
Good, that everybody understand what (and how) to do ;-)
https://github.com/jenkinsci/lockable-resources-plugin/commit/b2c3a73748e1276af288a7706157c30168a7de8a
I think there is wrong path in ' translation:' key.

**Comment by mPokornyETM** [comment]
@gounthar  can you pls retry it ? Thx

**Comment by gounthar** [comment]
I changed it before seeing your message, sorry about that.
I relaunched the synchronization, and it does not look bad now (see #371).
There is still (maybe) a problem, one of the property files seems to be missed by the configuration (because higher in the path).

**Pull request merged**
