### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by gounthar**

### CODE REVIEW

**Comment by mPokornyETM** [comment]
LGTM

**Review by mPokornyETM — APPROVED** [review]
thx

**Comment by mPokornyETM** [comment]
> thx

I am trying now to get help from my work colleagues
 German && Spain
 Finish, Hungarian and french shall be also possible

My native language (Slovakia) is missing, but fine with them.

**Comment by gounthar** [comment]
I think I'll be able to add your language. 
Thanks. 🤗

**Comment by mPokornyETM** [comment]
@gounthar Do you know, is there some way to invite some guest? My friends has no GithHub NOR crowdin account

**Comment by gounthar** [comment]
> @gounthar Do you know, is there some way to invite some guest? My friends has no GithHub NOR crowdin account

There is something about that in Crowdin, let me check what we can do.

**Comment by gounthar** [comment]
> > @gounthar Do you know, is there some way to invite some guest? My friends has no GithHub NOR crowdin account
> 
> There is something about that in Crowdin, let me check what we can do.

There is something called [Crowdsourcing](https://jenkins.crowdin.com/u/projects/26/crowdsource), where we could set up a Readme, a logo, and (soon) gamification.
We can also find there a status image we could embed like this:
[Crowdin](https://jenkins.crowdin.com/lockable-resources-plugin).

We can also find there a direct [link](https://jenkins.crowdin.com/lockable-resources-plugin) to the translation project, and templates to share that on twitter (I'll do it asap with my account).

Unfortunately, participating in translating with Crowdin implies you open an account there. 🤷‍♂️

**Comment by gounthar** [comment]
Done: https://twitter.com/Poddingue/status/1585976772125810688

**Comment by gounthar** [comment]
I added Slovak. 👍

**Comment by mPokornyETM** [comment]
> Done: https://twitter.com/Poddingue/status/1585976772125810688

Many thanks.  I don't use twitter, but I will try to ask my wife for sharing. It means indirect contribution.   😁

**Comment by mPokornyETM** [comment]
And thanks for slovakian language

**Comment by gounthar** [comment]
Houston, we may have a problem.
It looks like there are two packages with properties:
 - `io.jenkins`
 - `org.jenkins`

One of them must be wrong...

**Comment by mPokornyETM** [comment]
> Houston, we may have a problem. It looks like there are two packages with properties:
> 
> * `io.jenkins`
> * `org.jenkins`
> 
> One of them must be wrong...

'Apollo, yes we known that'. ;-) But I have no idea why. It looks copy && paste

**Comment by mPokornyETM** [comment]
So definitely comming from me. I will try to remove it, and test it again. Sorry for the waste

**Comment by gounthar** [comment]
I was not looking for someone to put the blame on. 😊 
It's maybe my fault because the Crowdin UI showed me that the config file was not giving any file to translate.
I then moved the path that was defined in it to allow Crowdin to find the property files to translate.
I will try to revert the merge while we're looking for a solution.

**Comment by gounthar** [comment]
@mPokornyETM could you please review #370 ?
Thanks.

**Pull request merged**
