### PR TITLE
Replace deprecated method calls

### PR DESCRIPTION
**Pull request by offa**
Replaces deprecated methods and some minor clean-up.

------------------------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by offa** [comment]
I've applied formatting to the changed files, this introduced quite some diff. Feel free to drop the formatting commit.

**Comment by jimklimov** [comment]
Thanks, at least the deprecated part makes sense :)

The formatting, was it done by applying some encoded definition (e.g. would IDEs or mvn recipes uphold/enforce it anyway), or a manual pick of taste? I agree with half of the changes but not another half :) e.g. the method args are much more readable with one long arg per line, comments wrapped to under 80 chars, etc. are not something to comfortably lose.

**Comment by jimklimov** [comment]
For codebase markup, see also #293

**Comment by offa** [comment]
> The formatting, was it done by applying some encoded definition (e.g. would IDEs or mvn recipes uphold/enforce it anyway), or a manual pick of taste? 

I have applied the google style as documented in the readme (using `mvn fmt:format` on each changed file).

**Comment by jimklimov** [comment]
UPDATE: Resolved spacing conflicts after merge of #293 for (hopefully) more consistent changes across the board.

**Comment by jimklimov** [comment]
Seems the maven format wraps long lines around 100 chars; is there a way to change that to ~80 (76?) char limit, to match default terminal size (I do still edit in those text-mode tools mostly), or is that nowadays a battle against windmills?

**Comment by offa** [comment]
Hmm … docs don't mention a setting like this unfortunately. But I'm not very familiar with it.

**Comment by basil** [comment]
Released in [2.15](https://github.com/jenkinsci/lockable-resources-plugin/releases/tag/lockable-resources-2.15).

**Pull request merged**
