### PR TITLE
Add reservedTimestamp field

### LINKED ISSUE #225: Add reserved timestamp field in locable resource list
Sometimes, it is good to know when a resource was reserved/locked.

For instance, if it was locked for a few hours or even days, it should be ok but after weeks/months you could probably unreserve it without any problems.

The timestamp value should be set automatically when a resource is reserved/locked and clear after resource unreserve or unlocked.

### PR DESCRIPTION
**Pull request by primoz-p**
* added reservedTimestamp field
* display it in lockabkle resource page
* added unit tests 

Fixes #225

### CODE REVIEW

**Comment by offa** [comment]
@TobiX can you have a look at the PR? It's a really useful feature.

**Comment by offa** [comment]
Ping @basil

**Comment by basil** [comment]
Hi @offa, I will look at this eventually but it is going to take some time. I am not currently familiar with this codebase, so I will need to spend some time reading the code and fixing some bugs before I can review new features.

**Comment by offa** [comment]
No problem, thanks for the info!

**Comment by rnickle79** [comment]
Any chance this can be included in the next release?

**Comment by offa** [comment]
Is there a chance to revive this PR?

**Comment by bignay2000** [comment]
Just added this plugin to my deployments, a time stamp would be very useful!

**Comment by basil** [comment]
@offa Are you interested in becoming a maintainer of this plugin? Feel free to file a `repository-permissions-updater` PR and I'll approve.

**Comment by offa** [comment]
I can't commit as a maintainer unfortunately. But I try to give a helping hand here and there.

**Comment by jimklimov** [comment]
Thanks @primoz-p for the feature and to @offa handling the PR concerns above via PR #273, and for patience! :)

**Pull request closed without merging**
