### PR TITLE
update project id

### PR DESCRIPTION
**Pull request by mPokornyETM**
update crowdin project id

#356 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira

### CODE REVIEW

**Comment by mPokornyETM** [comment]
@NotMyFault  can you pls look here. Thx

**Comment by NotMyFault** [comment]
> @NotMyFault can you pls look here. Thx

What am I supposed to look for?

**Comment by mPokornyETM** [comment]
Kindly ask, to be sure I do it in correct way. It is 'new' feature and I thing nobody here has some experience.

**Review by NotMyFault — APPROVED** [review]
All good, yea, that is the correct way to set a project ID 👍🏻

**Review by gounthar — APPROVED** [review]
Looks good to me too. Thanks. 👍

**Pull request merged**
