### PR TITLE
Api 2.0

### PR DESCRIPTION
**Pull request by Epsilon-B**
This is a proposed API 2.0.
The main proposal is to allow other developpers to interact with the lockable resources plugin (with code addition or even third party plugins).
I have pinpointed two main functionalities:
- the selection of the next waiting job (due to resources starvation): one may want to use specific algorithms to select the next job according to various criteria: user id, needed resources, build duration, (moon phase), etc.
- the resources selection: some resources may be less expensive, more stable, with capabilities more common among all the resources, etc.

So I have create two base classes for these identified cases:
- QueuePolicy: 
  - sort() => sort the waiting contexts (jobs)
  - select() => select the next context (job) to execute

- ResourcesSelector: 
  - sortResources() => sort the given ressources
  - selectResources() => select the resources to use among given list
  - getFreeResources() => return the resources list considered as "free" (ie. usable)

Please give me feedback about this proposition.
We can surrely improved the customization part of this great plugin, so it may become a "must have" for Jenkins users.

I am absolutly not an expert of Jenkins architecture, so I welcome any advice / criticism / idea to improve the plugin.

### CODE REVIEW

**Comment by roidelapluie** [comment]
would be great to have a lockItMaybe() functions that returns false if the lock is already taken

**Comment by orosen** [comment]
Not sure if this is in the scope of your work, but it would be very handy to be able to use a build parameter as the resource name to lock in the job. So jobs that use build parameters to decide on which hardware to run on, can dynamically choose the correct lock.

**Comment by roidelapluie** [comment]
@orosen you can use Jenkins Pipeline for this

**Comment by Epsilon-B** [comment]
@roidelapluie : 
If your request deals with API function, there was already a function "LockableResourcesManager.tryLock()" (for pipeline usage).
However I concede its name is not clear: so I have renamed it "lockNowOrLater()".
Moreover, I have added "lockNowOrNever()" which is probably matching your request (+ used for freestyle jobs within "LockRunListener.onStarted()").

If your request deals with a new pipeline keyword, I am currently trying to add a new keyword "trylock" for optional blocks. But I am facing some issues with the block return code (true/false should be nice).
For exemple:
```
stage 'Try lock not blocking' {
    while(true) {
        a = trylock(resource: 'resource1') {
            echo 'Do something only if resource1 is available'
        }
        echo 'Has been executed=' + a
        if(a) {
            break
        } else {
            echo 'Do something before retrying to lock resource1'
        }
    }
}
```

**Comment by Epsilon-B** [comment]
@orosen:
For pipeline project, as suggested by @roidelapluie, you can use the following syntax ("label/labels" are synonyms for "capability/capabilities"):
```
lock(resource: 'resource1 resource2', resources: ['resource1', 'resource2'], 
    label: 'label1 label2', labels: ['label1', 'label2'],
    capability: 'label1 label2', capabilities: ['label1', 'label2'],
    quantity: 2, variable: 'MY_VAR') {
        ... execution block ...
}
```

For freestyle (legacy) jobs, I have already added a new property that is probably matching your request.
With this property, in job configuration panel, you can force required/prohibited resources capabilities, and set the default capabilities/resources selection at runtime.

image

image

At runtime, the user will be able to select the resource(s) according to the required/prohibited.

image

**Comment by Epsilon-B** [comment]
I have added a "trylock" directive/closure for pipeline usage.
It works exactly as the "lock" directive/closure except that it is non blocking in case of unavalaible ressource.
In details, when the closure is started:
- if available, the required ressources are locked immediatly and the instructions within the closure are executed: the closure returned value is "true"
- if not available, no ressource is locked and the instructions within the closure are ignored (not executed): the closure returned value is "false"

This feature prevent the pipeline code to freeze if the lock is not possible, and allow to perform fallback/background tasks.
For example:
```
stage 'Try lock not blocking' {
    while(true) {
        a = trylock(resource: 'resource1') {
            echo 'Do something only if resource1 is available'
        }
        echo 'Has been executed=' + a
        if(a) {
            break
        } else {
            echo 'Do something before retrying to lock resource1'
        }
    }
}
```

**Comment by Epsilon-B** [comment]
I have added a timeout parameter (expressed in seconds, can be fractional since a 'Double') in both pipeline lock step and freestyle job.
For exemple:
```
lock(resource: 'resource2', timeout: 600) {
        ... execution block ...
}
```

image

**Comment by robin-jarry** [comment]
Hi @Epsilon-B 

Thanks for your PR. This looks interesting. Unfortunately, this is too much to review at once.

A few general remarks on what I could see:

* Rebase on master, fix merge conflicts.
* Remove trailing spaces, newlines.
* Use UNIX line endings `\n`, NOT windows.
* Reduce the number of commits by squashing by topic.
* Write meaningful commit logs. This helps understand what the change is about. One line is usually not enough.
* Avoid unnecessary changes (i.e. code move) mixed with actual changes. This makes code review harder (if not impossible). If you want to do code cleanup or refactoring, do it in separate commits, or better, in a separate PR.

Read this for inspiration: http://wiki.qemu.org/Contribute/SubmitAPatch

After a proper cleanup/reorganization and rebase on the master, code review will be easier.

**Comment by robin-jarry** [comment]
From a user point of view, here is a suggestion:

When a job needs to lock multiple resources based on capabilities, there is no way to know what resources have what capabilities using the "Variable name" in shell scripts.

Maybe a solution would be to export the actual names of locked resources using something similar to "Variable name", but per "Required resource" item.

Here is a screenshot for illustration:

image

**Comment by ceztko** [comment]
Today I needed exactly this just to discover this PR stalled 3 years ago :(

**Comment by tomasbjerre** [comment]
I implemented `tryLock` and `releaseLock` steps in:
https://github.com/jenkinsci/lockable-resources-plugin/issues/164

**Comment by TobiX** [comment]
Unfortunatly, this pull request has stalled long before I adopted this plugin and it's sheer size and scope is just overwhelming. Therefore, I'm closing this pull request. If someone wants to revive it, I'd suggest splitting it in smaller, more manageable chunks and open new pull request for single features.

**Pull request closed without merging**
