### PR TITLE
Node reservation

### PR DESCRIPTION
**Pull request by darius-m**
Added functionality for reserving resources as a per node basis.

Notes: 
- This pull request includes the documentation commits from https://github.com/jenkinsci/lockable-resources-plugin/pull/14, because adding the feature based on the current master would generate a conflict anyway between this branch and the documentation branch.
- This branch is a basis for a future pull request introducing automatic generation of node reserved resources based on node labels.

### CODE REVIEW

**Comment by eddyp** [comment]
Just as a note, we used successfully this feature in one of our jobs to distribute embedded test execution jobs between various nodes to which boards were connected via JTAG (one board per node).

The idea was to make sure no two execution jobs would be ran on the same node at the same time since that would mean both would want to use the same board.

**Comment by darius-m** [comment]
Added issue https://issues.jenkins-ci.org/browse/JENKINS-30056 on Jira, as a new feature.

**Comment by lucaf86** [comment]
Reserving resources as a per node basis is exactly what I'm searching for my Jenkins CI.
There is a similar plugin which provide the possibility to get exclusive access to a resource tied to a specific node [https://wiki.jenkins-ci.org/display/JENKINS/External+Resource+Dispatcher](url) but it's old and no more supported.
I'm searching for something similar and it looks like that this pull request add to lockable resources plugin a similar functionality.
I see that this post is of last year, so I was wondering if this pull request is still usable? and if is planned a merge to the master?

I also tried to clone upstreaming:node-reservation branch but there is something broken on it, the jenkins plugin is not created due to errors on that branch.

**Comment by darius-m** [comment]
The pull request should still be usable, but a merge is not planned as far as I am aware.
As far as errors are concerned, when the pull request was created there were no such errors, so they must be caused by newer revisions of the build software. I will attempt to look into that, and will try to provide an answer in roughly two weeks.

**Comment by roguishmountain** [comment]
@darius-m have you done any further work on making this PR mergable?

**Comment by darius-m** [comment]
@roguishmountain I'm afraid I wasn't able to put enough time into it. Unfortunately, there's not a lot of spare time right now, so I'd say that chances for a fix are slim until July-August. I will see what I can do until then

**Comment by darius-m** [comment]
Hi, I have updated the code for merging with the master. The application seems to run correctly on the local machine, but the automatic commit checker fails for some reason.
The intended functionality seems to have been preserved, but testing was done on a rather small test, since testing in a network is not an option at this time.

Feedback is appreciated.

**Comment by eddyp** [comment]
Thanks, Darius!

**Comment by darius-m** [comment]
If someone with a better understanding of the test framework could provide some feedback on the failing tests, it would help a lot. At least two of the tests seem to work (I am running Jenkins in an IDE using the web interface), as resources are locked and tests do start.

**Comment by darius-m** [comment]
Fixed by removing part of the 'approvalRequired' test since the assertions could never be true.

**Comment by TobiX** [comment]
I consider this feature out-of-scope for this plugin. If someone wants to revive this effort, I would propose creating an extension point for "dynamic labels" and adding this feature using a new plugin extending this one.

**Pull request closed without merging**
