### PR TITLE
Match BOM artifact to jenkins.version used

### PR DESCRIPTION
**Pull request by alecharp**
In #632, the `jenkins.version` was bumped from `2.387.3` to `2.440.1` but the BOM was not.
I discovered that during BOM release.

I cannot prove that this on its own would fix the BOM release.

### Testing done

I ran `mvn verify` locally with no problem.

### Proposed upgrade guidelines

N/A

### Localizations

- [ ] English
- [ ] German
- [ ] French
- [ ] Slovak
- [ ] Czech
- [ ] ...

### Submitter checklist

- [ ] The Jira / Github issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - The changelog generator for plugins uses the **pull request title as the changelog entry**.
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during the upgrade.
- [x] There is automated testing or an explanation that explains why this change has no tests.
- [ ] New public functions for internal use only are annotated with `@NoExternalUse`. In case it is used by non java code the `Used by {@code <panel>.jelly}` Javadocs are annotated.

- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease the future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
- [ ] Any localizations are transferred to *.properties files.
- [ ] Changes in the interface are documented also as [examples](src/doc/examples/readme.md).

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There is at least one (1) approval for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the **pull request title** and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically. See also [release-drafter-labels](https://github.com/jenkinsci/.github/blob/ce466227c534c42820a597cb8e9cac2f2334920a/.github/release-drafter.yml#L9-L50).
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] java code changes are tested by automated test.

### CODE REVIEW

**Review by gounthar — APPROVED** [review]
Looks good to me 👍

**Comment by alecharp** [comment]
I have the same two tests failures locally. Not sure it's "flaky".

**Comment by gounthar** [comment]
I also have several tests failing:

```
[ERROR] Tests run: 31, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 355.6 s <<< FAILURE! -- in org.jenkins.plugins.lockableresources.LockStepTest
[ERROR] org.jenkins.plugins.lockableresources.LockStepTest.unlockButtonWithWaitingRuns -- Time elapsed: 180.1 s <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 180 seconds
        at java.base/java.lang.Object.wait0(Native Method)
        at java.base/java.lang.Object.wait(Object.java:366)
        at org.jenkinsci.plugins.workflow.test.steps.SemaphoreStep.waitForStart(SemaphoreStep.java:169)
        at org.jenkins.plugins.lockableresources.LockStepTest.unlockButtonWithWaitingRuns(LockStepTest.java:767)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[INFO] Running org.jenkins.plugins.lockableresources.LockStepWithRestartTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 78.36 s -- in org.jenkins.plugins.lockableresources.LockStepWithRestartTest
[INFO] Running org.jenkins.plugins.lockableresources.LockableResourceApiTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.96 s <<< FAILURE! -- in org.jenkins.plugins.lockableresources.LockableResourceApiTest
[ERROR] org.jenkins.plugins.lockableresources.LockableResourceApiTest.reserveUnreserveApi -- Time elapsed: 16.03 s <<< FAILURE!
java.lang.AssertionError:

Expected: is <true>
     but: was <false>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.jenkins.plugins.lockableresources.LockableResourceApiTest.reserveUnreserveApi(LockableResourceApiTest.java:41)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[INFO] Running org.jenkins.plugins.lockableresources.LockableResourceManagerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.79 s -- in org.jenkins.plugins.lockableresources.LockableResourceManagerTest
[INFO] Running org.jenkins.plugins.lockableresources.LockableResourceRootActionSEC1361Test
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.96 s -- in org.jenkins.plugins.lockableresources.LockableResourceRootActionSEC1361Test
[INFO] Running org.jenkins.plugins.lockableresources.LockableResourceTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 s -- in org.jenkins.plugins.lockableresources.LockableResourceTest
[INFO] Running org.jenkins.plugins.lockableresources.NodesMirrorTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.34 s -- in org.jenkins.plugins.lockableresources.NodesMirrorTest
[INFO] Running org.jenkins.plugins.lockableresources.PressureTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 84.47 s -- in org.jenkins.plugins.lockableresources.PressureTest
[INFO] Running org.jenkins.plugins.lockableresources.actions.LockableResourcesRootActionTest
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.52 s -- in org.jenkins.plugins.lockableresources.actions.LockableResourcesRootActionTest
[INFO] Running org.jenkins.plugins.lockableresources.util.SerializableSecureGroovyScriptTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 s -- in org.jenkins.plugins.lockableresources.util.SerializableSecureGroovyScriptTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   LockableResourceApiTest.reserveUnreserveApi:41
Expected: is <true>
     but: was <false>
[ERROR] Errors:
[ERROR]   LockStepTest.unlockButtonWithWaitingRuns:767->Object.wait:366->Object.wait0:-2 » TestTimedOut test timed out after 180 seconds
[INFO]
[ERROR] Tests run: 165, Failures: 1, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:56 min
[INFO] Finished at: 2024-04-19T14:58:41Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project lockable-resources: There are test failures.
[ERROR]
[ERROR] Please refer to /home/ubuntu/lockable-resources-plugin/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Review by basil — CHANGES_REQUESTED** [review]
https://github.com/jenkinsci/lockable-resources-plugin/pull/642#issuecomment-2040535681

**Pull request closed without merging**
