### PR TITLE
Implement candidate-cache for resource-selection to prevent performance-regression

### PR DESCRIPTION
**Pull request by gmc-devel**
This suggested change will prevent a (mostly exhausting) performance-regression if the resource-candiates will be choosen by a groovy-script or a given label 1). This is implemented by a cache which stores the resource-canditates for the next 5 minutes for the specific task (queue-item).
A resource-removement within this cache-time will be considered, but new resources are included after this cache-timeout; I.e., if the candidates are determined again.

1) The cache will also be used on label-selection. But this is not as time-consuming like using a groovy-script.

Note: In our case (many resources and freestyle-/matrix-jobs) this change has fixed a noticeable regression of the UI if there were a lot of these builds (with script-selection) in the queue.

### CODE REVIEW

**Comment by TobiX** [comment]
Can you provide a test case?

**Comment by gmc-devel** [comment]
Hi!

> Can you provide a test case?

I'm not sure how to provide and test this issue/implementation. Apart from the fact that I'm not "really" familiar with Java, this implementation provides a tranparent cache and follows the idea: The list of potential resource-canditates is time invariant for a specific build wating for resources (as long the configuration does not change).

Removing a resource-item from the configuration will also lead to removing this item from a cached candidate-list. But new (added) ressource-items and also changing the groovy-script will be taken into account on the next evaluation (i.e. after the time-out of the previously cached answer).
At least,  we have to assume that the list of resources and also the selection-criteria (groovy-script) is stable and therefore also the list of candidates is stable for a (currently) waiting build;
IMHO, If a build have waits more than 5 minutes (cache-timeout) a re-evaluation will be done to take any configuration-changes into account.

In our case (using a private variant of this plug-in), this fix has improved the performance extremly.
E.g.,  processing of more than 15 builds at the same time and over 20 configured resources leads to >= 300 (groovy-) evaluations. But this occurs periodically and has to be finished within 5 seconds (hard-coded queueing-interval) or the UI (and other scheduled processes) will hang and sometimes it was necessary to re-start the complete build-farm (bacause of a kind of dead-lock; no progress over hours).

Best regards from Salzburg,
Markus

**Comment by jimklimov** [comment]
We have been using this changeset in our private build of the plugin, along with applying some other PRs that are still open, and possibly this result-caching has indeed reduced the load on Jenkins controller when we have less resources available (0 in the extreme case) than queued jobs wanting them, with resource applicability evaluated by a groovy script (to rule out testing on devices that de-facto are not accessible at the moment, e.g. "soft-died" after the last tested firmware build).

Frankly, another probably contributing remedy for our situation is a regular run of a scripted pipeline job which inspects the device viability in a similar manner, and "directly" assigns them to a special user "Holder of Broken Stuff" or takes away from it if the device was revived. This way, Lockable Resources do not even try to look into such a device as it is just not available in the usual manner.

Since this was done, we had far fewer cases of Jenkins controller becoming nearly unresponsive (taking minutes to progress through job stages and assign the build verdicts) when all devices were dead and no resources available to the test jobs, and the controller was just intensively and infinitely looping to check if some came back. That became its only activity, in effect.

**Comment by jimklimov** [comment]
Somehow this breaks the test for #279 (which is in master branch now). Several recent builds of master passed green, and several retries of this PR failed with unexpected strings popping up in build logs.

**Comment by jimklimov** [comment]
My *guess* about what happens with this really small change is that sometimes the test run can cache the result of resource evaluation (at point "cause 1-5" it remembers that within last 5 minutes the resource was occupied by "test2-1") and sometimes based on timing/frequency of checks it maybe does not.

I wonder if the caching makes sense for resources selected by label (scripts are unpredictably CPU consuming, labels may be less so - depending on amount of resources times labels defined, though).

Also I wonder if the methods responsible for freeing the resource (unlock, unreserve, reset... maybe others like setReservation where they set the value to null) should update the `cachedCandidates` with either an entry that the resource is known available, or removing the entry for that resource so it would be re-evaluated next time - not sure which one makes more sense.

@gmc-devel - are you available to chime in with thoughts or code, please? :)

**Comment by jimklimov** [comment]
Trying a helper method to remove the `candidate` from queues that have it cached, so it would be re-evaluated, as part of unlock/unreserve via LRM.

**Comment by jimklimov** [comment]
Looking at the log, I just can't unambiguously implicate this PR. Seems the `semaphore` blocked somehow, sometimes?..

````
   8.425 [p #1] Finished: ABORTED
   8.425 [p2 #1] Lock acquired on [resource1]
   8.425 [p2 #1] [Pipeline] {
Blocking wait-inside/2
Planning to unblock wait-inside/2 as success
   8.475 [p2 #1] [Pipeline] semaphore
 180.000 [id=1]	WARNING	o.j.hudson.test.JenkinsRule$2#evaluate: Test timed out (after 180 seconds).
"Executing hardKillNewBuildClearsLock(org.jenkins.plugins.lockableresources.LockStepHardKillTest)" Id=15 Group=main RUNNABLE
````

Test code that failed here was:
````
    WorkflowJob p2 = j.jenkins.createProject(WorkflowJob.class, "p2");    
    p2.setDefinition(   
        new CpsFlowDefinition(    
            "lock('resource1') {\n" +  
            "  semaphore 'wait-inside'\n" + 
            "}", true));
    WorkflowRun b2 = p2.scheduleBuild2(0).waitForStart();  

...

    // Verify that b2 gets the lock.   
    j.waitForMessage("Lock acquired on [resource1]", b2);  
    SemaphoreStep.success("wait-inside/2", b2);  
    // Verify that b2 releases the lock and finishes successfully.   
    j.waitForMessage("Lock released on resource [resource1]", b2);   
    j.assertBuildStatusSuccess(j.waitForCompletion(b2));   
    isPaused(b2, 1, 0); 
````

Added a message to `echo 'Semaphore 2 unblocked'` in the test so if future runs break similarly, we'd see if the semaphore was passed and the problem is with unlocking, or if it is the semaphore problem indeed.

**Comment by gmc-devel** [comment]
Hi @jimklimov !

The origin idea of this implementation to cache all potential candidates (selected by label or script) regardless whether a candidate is usable (locked, reserved or already queued); I.e., it should avoid the time-consuming selection (before filtering) each time. At least, I'm not really a Java-developer, but (IMHO) as I know a Java List (like cached candidates) is a list of references. The candidate-list (got from the cache) contains only objects which were also known at evaluation time and it was necessary tot remove objects which are no longer known (I.e, deleted from the global resource-list in the meantime).

At the moment I'm not sure that I understand all aspects of uncacheIfFreeing(). It will remove a candidate after unlocking or unreserve from the cache-list (for each evaluation/queue-id) and if this list is empty the cache-entry will be invalidated to enforce a re-evaluation (next time). Up to now, I've use this plugin for freeestyle- and matrix-jobs and I have to take a deeper lock insight using lockable-resources in pipeline-jobs ... QU: Why is a candidate removed from this list of candidates after unlock/unreserve - this list contains potential candidates regardless of their current state (usability) ?
I have to think about your test a side-effects on timing if there's no cache-update like uncacheIfFreeing().

Best regards from Salzburg,
Markus

**Pull request merged**
