### PR TITLE
Allow multiple required resources on job configuration

### PR DESCRIPTION
**Pull request by jlrigau**
This PR allows to add multiple required resources on job configuration in order to be able to reserve multiple resource with different label and for having the possibility to use a distinct environment variable for each required resources.

screen shot 2016-09-07 at 18 36 21

An important refactoring has been done for allowing this feature so any feedback is welcomed.

### CODE REVIEW

**Comment by amuniz** [comment]
This is conflicting with #26, although #26 is only Pipeline-related.
Maybe you can start from that PR and complete it for Freestyle projects also?

**Comment by Aeon512** [comment]
@jlrigau from my point of view #26 is complete and just awaits merging. 
Build is successful locally and why the CI fails is out of my knowledge. 

About which build failures do you talk? Do you have local failures?

I would second @amuniz approach to base your solution on #26 and merge everything together

**Comment by ssbarnea** [comment]
Is this still needed or was included in #42 ?

**Comment by barnish** [comment]
We would like to see this functionality added to the lockable-resource plugin and it seems o be partially available in pipeline flow anyway,
I opened [JENKINS-42209](https://issues.jenkins-ci.org/browse/JENKINS-42209) for that issue.

**Comment by TobiX** [comment]
Progress on this change seems to have stalled. As written in [JENKINS-42209](https://issues.jenkins-ci.org/browse/JENKINS-42209), this is already available for pipeline jobs. I would be willing to merge an up-to-date minimal pull request adding this feature, but I won't be able to spend any time implementing it myself. Therefore, I'm closing this for now. Feel free to reopen after resolving the conflicts.

**Pull request closed without merging**
