### PR TITLE
Fix unclosed brackets in `lockable-resources.js`

### PR DESCRIPTION
**Pull request by yaroslavafenkin**
See https://github.com/jenkinsci/lockable-resources-plugin/issues/722.

### Testing done

Go to lockable resources page, observe there's an error in the dev console before the change. Reserve button doesn't work.

After the change there's no error, reserve/unreserve buttons work as expected.

[Before the change](https://www.youtube.com/watch?v=9pRF7oa2hzU)
[After the change](https://www.youtube.com/watch?v=wt9zN5YIbnY)

### Proposed upgrade guidelines

N/A

### Localizations

- [ ] English
- [ ] German
- [ ] French
- [ ] Slovak
- [ ] Czech
- [ ] ...

### Submitter checklist

- [x] The Jira / Github issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - The changelog generator for plugins uses the **pull request title as the changelog entry**.
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during the upgrade.
- [ ] There is automated testing or an explanation that explains why this change has no tests.
- [ ] New public functions for internal use only are annotated with `@NoExternalUse`. In case it is used by non java code the `Used by {@code <panel>.jelly}` Javadocs are annotated.

- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease the future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
- [ ] Any localizations are transferred to *.properties files.
- [ ] Changes in the interface are documented also as [examples](src/doc/examples/readme.md).

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There is at least one (1) approval for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the **pull request title** and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically. See also [release-drafter-labels](https://github.com/jenkinsci/.github/blob/ce466227c534c42820a597cb8e9cac2f2334920a/.github/release-drafter.yml#L9-L50).
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] java code changes are tested by automated test.

### CODE REVIEW

**Comment by yaroslavafenkin** [comment]
@basil PTAL when you're around

**Review by mPokornyETM — COMMENTED** [review]
The change looks fine, but please fill the PR description from template.
How you test it? Some screenshots. Why we missed automated test cases? .....
All this informations are helpfull in the review process checking the history make it also much more easy.

**Comment by yaroslavafenkin** [comment]
> The change looks fine, but please fill the PR description from template. How you test it? Some screenshots. Why we missed automated test cases? ..... All this informations are helpfull in the review process checking the history make it also much more easy.

Both CSP PRs that I've filed before were fine individually. The lack of bracket is caused by a merge accident. Seems to be first introduced in https://github.com/jenkinsci/lockable-resources-plugin/pull/719/commits/c0ba76f95f5501d2b5e0ffd1d95fa195d055cdd0. Videos of testing of those changes are in the corresponding pull requests.

**Review by basil — APPROVED** [review]
Sorry for the trouble and thanks for fixing this.

**Pull request merged**
