### PR TITLE
Added button to copy resource name to clipboard

### PR DESCRIPTION
**Pull request by primoz-p**
* small change with useful effect
* used **copyButton** jelly tag

### CODE REVIEW

**Comment by primoz-p** [comment]
It looks like there are some problems with Jenkins instance used for testing?!?!?!

**Comment by TobiX** [comment]
Thanks. Would be nice if the messages were translatable, but I currently can't quite remember how that works for Jelly templates 😆

**Comment by primoz-p** [comment]
> Thanks. Would be nice if the messages were translatable, but I currently can't quite remember how that works for Jelly templates 😆

I really didn't bother with that because there are more or less no texts translatable in this plugin. I will check anyway how hard is it to make them translatable.

**Comment by jimklimov** [comment]
Thanks for the feature and handling the PR concerns above, and for patience! :)

**Pull request merged**
