### PR TITLE
Reserved resources available again after reloading CasC configuration

### LINKED ISSUE #527: Reserved resources available again after reloading CasC configuration
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.411
OS: Linux - 6.3.8-100.fc37.x86_64
Java: 11.0.19 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
bootstrap5-api:5.3.0-1
bouncycastle-api:2.28
branch-api:2.1109.vdf225489a_16d
caffeine-api:3.1.6-115.vb_8b_b_328e59d8
checks-api:2.0.0
cloudbees-folder:6.815.v0dd5a_cb_40e0e
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
credentials:1254.vb_96f366e7b_a_d
credentials-binding:604.vb_64480b_c56ca_
data-tables-api:1.13.4-3
display-url-api:2.3.7
durable-task:507.v050055d0cb_dd
echarts-api:5.4.0-5
font-awesome-api:6.4.0-1
git:5.1.0
git-client:4.4.0
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jquery3-api:3.7.0-1
junit:1214.va_2f9db_3e6de0
lockable-resources:1172.v4b_8fc8eed570
mailer:457.v3f72cb_e015e5
matrix-project:789.v57a_725b_63c79
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
pipeline-build-step:496.v2449a_9a_221f2
pipeline-groovy-lib:656.va_a_ceeb_6ffb_f7
pipeline-input-step:468.va_5db_051498a_4
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2141.v5402e818a_779
pipeline-model-definition:2.2141.v5402e818a_779
pipeline-model-extensions:2.2141.v5402e818a_779
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2141.v5402e818a_779
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.3.0
scm-api:676.v886669a_199a_a_
script-security:1251.vfe552ed55f8d
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
ssh-credentials:305.v8f4381501156
structs:324.va_f5d6774f3a_d
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
workflow-aggregator:596.v8c21c963d92d
workflow-api:1215.v2b_ee3e1b_dd39
workflow-basic-steps:1017.vb_45b_302f0cea_
workflow-cps:3691.v28b_14c465a_b_b_
workflow-durable-task-step:1247.v7f9dfea_b_4fd0
workflow-job:1308.v58d48a_763b_31
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Fedora 37

### Reproduction steps

1. Add two lockable resources using "Configuration as Code" (without any note/reservedBy fields)
2. Reserve one resource
3. Add a note to the other resource
4. Reload the existing "Configuration as Code" configuration

### Expected Results

The first resource should still be reserved, the other should still have the note.

### Actual Results

The first resource is available again and the note of the other resource has been removed.

### Anything else?

As the status (reserved/free...), timestamp and the note or not really configuration properties, but more state properties, should they not be kept when reloading the CasC configuration? For the classic configuration in Jenkins (Manage Jenkins -> System), this works fine when e.g. adding resources (or just changing something else in the System settings). I think this is done with a call to copyUnconfigurableProperties() in https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/main/java/org/jenkins/plugins/lockableresources/LockableResourcesManager.java#L980.

### PR DESCRIPTION
**Pull request by mPokornyETM**
fix #527

### Testing done

Manuel tests in config page

Create jenkins instance with JCAC
Reserve resource in LRM page
restart jenkins
Resource is still reserved

### Proposed upgrade guidelines

N/A

### Localizations

N/A

### Submitter checklist

- [x] The Jira / Github issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - The changelog generator for plugins uses the **pull request title as the changelog entry**.
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during the upgrade.

### CODE REVIEW

**Comment by manosnoam** [comment]
Thanks for this PR @mPokornyETM. 
Was it not merged yet due to some checks ?

**Comment by mPokornyETM** [comment]
> Thanks for this PR @mPokornyETM. Was it not merged yet due to some checks ?

It has failed last time. I have no idea. It is long time ago. I merged master again into this branch. We will see if it works. WHen are the check green now, we canmerge it.

**Comment by manosnoam** [comment]
> It has failed last time. I have no idea. It is long time ago. I merged master again into this branch. We will see if it works. WHen are the check green now, we canmerge it.

Checks faile on `expected:<Reserved_A> but was:<null>` , I think you need to update the test too:
https://github.com/jenkinsci/lockable-resources-plugin/blob/f1ecb60981e246dd7a642c88dfdf9f029ad95f70/src/test/java/org/jenkins/plugins/lockableresources/ConfigurationAsCodeTest.java#L45

**Comment by mPokornyETM** [comment]
> > It has failed last time. I have no idea. It is long time ago. I merged master again into this branch. We will see if it works. WHen are the check green now, we canmerge it.
> 
> Checks failed on `expected:<Reserved_A> but was:<null>` , I think you need to update the test too:
> 
> https://github.com/jenkinsci/lockable-resources-plugin/blob/f1ecb60981e246dd7a642c88dfdf9f029ad95f70/src/test/java/org/jenkins/plugins/lockableresources/ConfigurationAsCodeTest.java#L45

thx for hit. I changed the test. Maybe now. But you are welcome to review this changes ;-)

**Comment by manosnoam** [comment]
> thx for hit. I changed the test. Maybe now. But you are welcome to review this changes ;-)

I think now `ConfigurationAsCodeTest.java` needs a formatting fix with `mvn spotless:apply`

**Comment by manosnoam** [comment]
All checks passed!
Who can review and approve?

**Comment by mPokornyETM** [comment]
> All checks passed! Who can review and approve?

you ;-)

**Comment by roded** [comment]
Hi, really looking forward for this fix.
I tried upgrading to the latest release which includes this fix and am still seeing the locks released after both a Jenkins restart or a CasC reload.

**Comment by mPokornyETM** [comment]
which version do used? The release '1310.v99ca_947ed698' has been published 1 hour ago. Has you this version?

**Comment by roded** [comment]
Yeah, I've upgraded just for this fix.

image

**Comment by kaltsi** [comment]
Happened to me too after a jenkins restart.
I was running Jenkins 2.462.1, updated plugins, upgraded Jenkins to 2.462.2 and updated plugins again.

All manually reserved resources had been released.

**Comment by kobihk** [comment]
+1 
After "Reload existing configuration" all the reserved resources were released to me too 
with: 
Jenkins Version 2.452.4 
Lockable Resources plugin Version1310.v99ca_947ed698

**Comment by mPokornyETM** [comment]
> Happened to me too after a jenkins restart. I was running Jenkins 2.462.1, updated plugins, upgraded Jenkins to 2.462.2 and updated plugins again.
> 
> All manually reserved resources had been released.

I see, my mistake. I does not understand it correctly. So I will revert the changes, open the issue again and try to find some other solution.

**Pull request merged**
