### PR TITLE
Paranoid security check

### PR DESCRIPTION
**Pull request by mPokornyETM**
eliminate issues founded by Jenkins Security Scan.
Some of this changes looks paranoid but it is the faster way to eliminate current security-check issues.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by mPokornyETM** [comment]
Great all currently opened security scan issues will be fixed
image

**Review by jmMeessen — APPROVED** [review]
LGTM!

Thank you for your contribution.

**Comment by Wadeck** [comment]
@mPokornyETM @jmMeessen As those web methods do not provide any "security impact", it's for your information.

💡 When you check for item being non null like in all those cases, you let users with just Overall/Read to call the methods, without a job before.

A `doXxx` method from a `Descriptor` can be called by using `http[s]://<jenkins-url>/descriptorByName/<canonicalNameOfTheDescriptor>/<webMethod>`. It means that your "protection" does not really protect anything as we were adding the `item` in this PR, the code was not using it / related to it beforehand.

Proposal:
```
if (item != null) {
   item.checkPermission(Item.CONFIGURE);
} else {
   Jenkins.get().checkPermission(Jenkins.ADMINISTER)
}
```
^ That will provide a real protection to your methods. 

⚠️ Now it's not necessary, but as there are a lot of people copy-pasting code from other plugins, that will prevent this kind of code to be reused in other location where the security is necessary.

**Comment by jmMeessen** [comment]
Thank you for this interesting and useful clarification, @Wadeck 

@mPokornyETM will you submit a new PR based on these suggestions or do you want me to submit it?

**Comment by mPokornyETM** [comment]
Need to be update tests, And I have no idea how to create Obejct of Item. So one example will be great. @jmMeessen  when you has time, it will be grate, when you provide it. Thx

@Wadeck  thx

**Comment by Wadeck** [comment]
> And I have no idea how to create Obejct of Item

In your code, it's automatically created because it's part of the URL (AncestorInPath). When you call `http[s]://<jenkins-url>/job/<jobName>/descriptorByName/<canonicalNameOfTheDescriptor>/<webMethod>`, the `job/<jobName>` part will ask Stapler to find that job and put it in the Ancestor list. In your method, you will receive that object automatically. You can try the behavior with the debugger, to see what Jenkins (Stapler) will provide you.

IOW the addition of `item` was a good idea, it's just not "complete". There is no need to provide a value to that variable, it's done automatically, my comment is about the usage of it that is not covering all cases.

**Comment by mPokornyETM** [comment]
> > And I have no idea how to create Obejct of Item
> 
> In your code, it's automatically created because it's part of the URL (AncestorInPath). When you call `http[s]://<jenkins-url>/job/<jobName>/descriptorByName/<canonicalNameOfTheDescriptor>/<webMethod>`, the `job/<jobName>` part will ask Stapler to find that job and put it in the Ancestor list. In your method, you will receive that object automatically. You can try the behavior with the debugger, to see what Jenkins (Stapler) will provide you.
> 
> IOW the addition of `item` was a good idea, it's just not "complete". There is no need to provide a value to that variable, it's done automatically, my comment is about the usage of it that is not covering all cases.

Thx, It is misunderstanding now. I know that is not covered as well, because this function was called also by test. And I add the 'null' as last call parameter in the test. I know that this is done automatic (somehow / magic for me), but how shall I create a instance from Item in the test file.

**Comment by Wadeck** [comment]
In an ideal world, you will test all code flow in your test.
- One with a user without permission
- One with a user with Job/Configure
and then, matrixing this with call with an item and a call without.

To "create" the item in the job, you can use `j.createFreeStyleProject()` like in [this test in core](https://github.com/jenkinsci/jenkins/blob/c25963cc485d8f8b35eb4ea0f02eff1547b61a3b/test/src/test/java/lib/form/ComboBoxTest.java#L173)
Now, with the test approach, there is no web request, which will make the retrieval of user more complicated.

Two approaches:
1) (**recommended**) You transform the `d.doCheckResourceNames(...)` into web requests, using `j.createWebClient()`, and having a dummy security realm with configured users and checking the URLs I mentioned in my previous comments ([example of code](https://github.com/jenkinsci/jenkins/blob/e27b310065b3c036b5fc9d123f1d1d99d3058c00/test/src/test/java/hudson/model/ComputerSetTest.java#L97-L135) with most of the methods)

2) Configuring a dummy security realm [1], and calling `SecurityContextHolder.getContext().setAuthentication(user.impersonate2())` (like in [TimeZonePropertyTest.java#L32)](https://github.com/jenkinsci/jenkins/blob/f29b4789834a7562b44d8c3a0abcd9fb0c927f27/test/src/test/java/hudson/model/TimeZonePropertyTest.java#L32))

[1]: Dummy security realm: 
```
j.jenkins.setSecurityRealm(j.createDummySecurityRealm());
j.jenkins.setAuthorizationStrategy(new MockAuthorizationStrategy()
    .grant(Jenkins.READ).everywhere().to("user")
    .grant(Jenkins.ADMINISTER).everywhere().to("manager")
);
```

(yeah it's not that simple ;) )

**Comment by mPokornyETM** [comment]
Great I will keep open the scan-issues and update the code as well. @jmMeessen  You must not care about the changes, I will do that after my business-hour ASSAP.

**Pull request merged**
