### PR TITLE
Reset resources on configuration update

### PR DESCRIPTION
**Pull request by R3d-Dragon**
I created a fix for the issue and tested it manually.

I would like to create a unit test for it but i have no experience in developing or testing jenkins plugins. So maybe @TobiX you can help me with that.

Basically i want to create a unit test for the `LockableResourceManager.configure()` method.
Therefore, i tried to perform a system config (global config) update and add/remove LockableResources. 

I saw similar approaches in other plugins where they are mocking the `StaplerRequest` in order to execute the `r.jenkins.reconfigure(...)` or `r.jenkins.doConfigSubmit(...)` method.

But i want to perform a regular config update without using mocks.
Do you have any idea how to achieve that?

### CODE REVIEW

**Comment by TobiX** [comment]
Please rebase to master first...

**Comment by TobiX** [comment]
You should be able to take the existing Configuration-as-Code tests as a template for new unit tests, I think...

**Comment by R3d-Dragon** [comment]
I did the rebase.

> You should be able to take the existing Configuration-as-Code tests as a template for new unit tests, I think...

Thanks for the fast response! From my perspective, this is no test case regarding the Configuration-As-Code feature. Therefore, these templates won't help.  

It's a test case for developing jenkins plugins (updating a plugin configuration via GlobalConfig UI). So i just need to find a way to test the `LockableResourceManager.configure()` method properly :)

**Comment by TobiX** [comment]
Since the change looked correct, I just went ahead and merged it - might add a test later.

**Pull request merged**
