### PR TITLE
Store table order and paging size a user select

### LINKED ISSUE #404: Lockable Resources "Show xxx entries" selection box option to change default entri
### What feature do you want to see added?

It would be practicle to have the option to select the default number of entries shown in the listview. I would like to have 100 instead of 10, but some others might want to have 50 etc.. The default selection should be saved for the next time you open the view.

lockable

### Upstream changes

_No response_

### LINKED ISSUE #411: First adopters complaints about new Lockable Resources Data Tables UI
### Jenkins and plugins versions report

Jenkins 2.361.4
Lockable Resources 1069.v726298f53f8c 

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux CentOS

### Reproduction steps

Had LR 2.18
Updated to current

Several complaints collected:

1. Sorting order (by value) vs. resource definition order (set by admin)
2. Items per page vs. refresh
3. Sorting order vs. refresh
4. Filtering vs. refresh

### Expected Results

UI usable (per habits and expectations spec for the team)

1. Sorting order (by value) vs. resource definition order (set by admin)

Resources most used by team members (e.g. SUTs left "stolen" for post mortems), as opposed to infrastructural and ephemeral resources, are on top of the list. Definition order (from global config / XML) with older tables ensured that.

2. Items per page vs. refresh
3. Sorting order vs. refresh
4. Filtering vs. refresh

If a choice is made (e.g. 100 items, Sort by name, filter to show items with "X" in... which field?) it is remembered when page is refreshed. Ideally it would be remembered for the user session/account so the cosmetic choice is not required every time you open the list (maybe except the filter).

### Actual Results

1. Sorting order (by value) vs. resource definition order (set by admin)

There does not seem to be a way to disable sorting by column values to revive sorting by definition order. This is almost a show-stopper for the team who now have to hunt for their dozen dedicated SUTs in the middle of hundreds of entries.

2. Items per page vs. refresh

When page refresh happens, it shows 10 items again

3. Sorting order vs. refresh

When page refresh happens, it shows default sorting again

4. Filtering vs. refresh

When page refresh happens, it shows all items again

### Anything else?

* Fallout of #375

* Similar concerns were raised in #404

* Same inconvenience issues with the lower table (list of labels and their usage)

* Default sorting order seems to have no real pattern to it. It does apply "Status" to put currently reserved entries on top, and according to header icons it then probably sorts by "Resource" name, but in fact the reserved entries are arranged randomly. Those currently free do seem to be alphabetically sorted by name.

* Table does not show the recently introduced timestamp field which was in 2.18 UI.
    * This info is useful, should be exposed.
    * Maybe sorting of reserved resources takes it into account "quietly"?

* Max of 100 items (or any max) may be inconvenient to some people. Can an option be added to show everything on one page?

* A suitable solution for teams that relied on old behavior may be to revive the old UI as a separate link and page, allowing more time and flexibility to perfect the new one.

### PR DESCRIPTION
**Pull request by mPokornyETM**
fix #411 
closes #404 

Fixed:
+ After few discussion with @uhafner it will be use the table.js script from DataTables. This allow to store user settings:
  + the order a user selects
  + paging size

Also we can spare a lot of code.

+ Added column 'Free in %' in labels table. It allows the user to sort most reserved / locked resources at the moment.

What is not fixed:
+ When user select one time the ordering it will be stored in browser storage and can not be removed (not by some UI action, can be removed from browser storage as well, but this is not common way) We can implement a button for that, but I thing it shall be implemented in data-tables-plugin instead (maybe it is time to contribute in other plugins too)
+ The dark theme. I will create an extra issue for that, because it has nothing to do with #411  I need more time for analysis, but this changes are important at the moment.

Note: I have try to store also filter text, but it provides more unclear view. There is no indicator in search field (that you has set it it) and you are wondering, why you see only few resources. Therefore I skip this idea.

### Testing done

There are few java changes but the changes are hit 100% by code coverage, therefore no new automatic tests. I provide many manual tests and it looks pretty good.
Ordering and paging size are stored for both tables. It works in following cases:
+ page refresh
+ close browser and open page again
(tested with Chrome Version 107.0.5304.121 (Official Build) (64-bit))

### Proposed upgrade guidelines

N/A

### Localizations

- [x] English

Note: There is new key 'labels.table.column.percentage' which shall be translated by Crowdin. I tries my best to translate it in all supported languages, but I am not 100 % Sure (@gounthar maybe you can check French here)

### Submitter checklist

- [x] The Jira / Github issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during the upgrade.
- ~~[ ] There is automated testing or an explanation that explains why this change has no tests.~~
- ~~[ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.~~
- ~~[ ] New public functions for internal use only are annotated with `@NoExternalUse`. In case it is used by non java code the `Used by {@code <panel>.jelly}` Javadocs are annotated.~~
- ~~[ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.~~
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease the future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- ~~[ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.~~
- ~~[ ] For new APIs and extension points, there is a link to at least one consumer.~~
- [x] Any localizations are transferred to *.properties files.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There is at least one (1) approval for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [x] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [x] Proper changelog labels are set so that the changelog can be generated automatically.
- ~~[ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).~~
- [x] java code changes are tested by automated test.

### CODE REVIEW

**Comment by uhafner** [comment]
> * The dark theme. I will create an extra issue for that, because it has nothing to do with [First adopters complaints about new Lockable Resources Data Tables UI #411](https://github.com/jenkinsci/lockable-resources-plugin/issues/411)  I need more time for analysis, but this changes are important at the moment.

This is tracked as https://issues.jenkins.io/browse/JENKINS-68677

**Comment by mPokornyETM** [comment]
> > * The dark theme. I will create an extra issue for that, because it has nothing to do with [First adopters complaints about new Lockable Resources Data Tables UI #411](https://github.com/jenkinsci/lockable-resources-plugin/issues/411)  I need more time for analysis, but this changes are important at the moment.
> 
> This is tracked as https://issues.jenkins.io/browse/JENKINS-68677

@uhafner thx, I see the issue is open, But there are some parallel fixes. What shall be done to fix this issue also here?

**Comment by uhafner** [comment]
> > > * The dark theme. I will create an extra issue for that, because it has nothing to do with [First adopters complaints about new Lockable Resources Data Tables UI #411](https://github.com/jenkinsci/lockable-resources-plugin/issues/411)  I need more time for analysis, but this changes are important at the moment.
> > 
> > 
> > This is tracked as https://issues.jenkins.io/browse/JENKINS-68677
> 
> @uhafner thx, I see the issue is open, But there are some parallel fixes. What shall be done to fix this issue also here?

The last plugin that needs to be adapted is the data-tables-api-plugin. This plugin uses hard coded CSS values (BS5 light style), these CSS files need to be changed and read the Jenkins variables.

**Comment by mPokornyETM** [comment]
> 

Great, that means, I can ignore it here and maybe (when I find some time) fix it in the `data-tables-api-plugin.`

**Comment by jimklimov** [comment]
Jelly changes look like magic - in a good sense, less hardcoding, more functional :)

But I can't quickly test it at the moment, the server where we had many resources to lock is currently busy with endurance testing a new product release (so can't restart it).

On a side note, could any recent changes elsewhere break the self-tests? Or did they happen to be timing-dependent?
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Flockable-resources-plugin/detail/PR-415/9/pipeline/91
````
Expected "Locked resource reservedBy 1-5: null" got "Locked resource reservedBy 1-5: test2-1"
````

**Comment by mPokornyETM** [comment]
> Jelly changes look like magic - in a good sense, less hardcoding, more functional :)
> 
> But I can't quickly test it at the moment, the server where we had many resources to lock is currently busy with endurance testing a new product release (so can't restart it).
> 
> On a side note, could any recent changes elsewhere break the self-tests? Or did they happen to be timing-dependent? https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Flockable-resources-plugin/detail/PR-415/9/pipeline/91
> 
> ```
> Expected "Locked resource reservedBy 1-5: null" got "Locked resource reservedBy 1-5: test2-1"
> ```

Sorry for delay, but I try to split the columns in extra jelly pages, otherwise it is too complex and hard to read. But I am currently stuck with the reset button. It looks so that the code can not be hit.
About the failed tests. Yes in normal case it is about timing. In normal case, when I publish PR I starts tests on my dev node as well. When it fails on Jenkins side in normal case helps 'restart failed steps' I dont like it, but I have not time to fix the test as well. Sorry.

**Comment by mPokornyETM** [comment]
Hm I see it is not good idea. Loading jelly pages takes too long. I must find other solution

**Comment by mPokornyETM** [comment]
There are 2 testcases, their both takes ~50 seconds on my node. In that case the whole test script achieved 180 seconds timeout on slow nodes.  I will try to split this testcases to extra scripts to eliminate this scenario. It is very frustrating to make some changes, replays tests and hope that it do not achieved some timeout.  I try to eliminate the time consuming there, but both are to complex for me. I hope the split works. Otherwise I will revert test changes here. Has nothing to do with my changes and waste my time. 😪

**Pull request merged**
