### PR TITLE
[JENKINS-40368] Resources not unlocked after a hard kill

### PR DESCRIPTION
**Pull request by amuniz**
Fixing  [JENKINS-40368](https://issues.jenkins-ci.org/browse/JENKINS-40368)

The problem is that `LockableResourcesManager` is supposing a queued context will always have a valid linked build (waiting for the lock), but that turns to be false under some circumstances, like the one described in this issue: a hard killed job which for some other reason does not call `LockRunListener.onComplete` - something to be investigated separately. As it can happen if Jenkins is stopped abruptly so there is no chance to call anything, a fix here is needed regardless the potential fix upstream.

This fix also fixes the UI button to forcibly release a resource (which is throwing an exception when a queued context does not have a live build linked). With this fix the resource is released and the next context waiting for the lock proceeds.

@reviewbybees

### CODE REVIEW

**Comment by recampbell** [comment]
We really need a test for this use-case.

**Comment by amuniz** [comment]
> We really need a test for this use-case.

This is kind of a race condition I was not able to reproduce it consistently, so it's going to be difficult to write a test, but yes, it is worth a try.

**Comment by recampbell** [comment]
Perhaps something is possible using latches. Agree these are hard to test, but this seems like a key responsibility of this plugin.

**Comment by jglick** [comment]
Certainly reproducing a hard kill done at a particular time is easy—`SemaphoreStep.waitForStart` followed by `WorkflowRun.doKill`.

**Comment by rsandell** [comment]
:bee:

**Comment by abayer** [comment]
Ping @amuniz

**Pull request merged**
