### PR TITLE
LockableResourcesManager: make queueContext & unqueueContext thread safe

### PR DESCRIPTION
**Pull request by adelcast**
Both methods modify queuedContexts, but are not set to be synchonized,
which makes them vulnerable to a ConcurrentModificationException.

Signed-off-by: Alejandro del Castillo <alejandro.delcastillo@ni.com>

### CODE REVIEW

**Comment by dgeissl** [comment]
Would this one fix https://issues.jenkins-ci.org/browse/JENKINS-44597 ?

**Comment by adelcast** [comment]
I believe it can, yes. While getNextQueuedContext is not synchronized, is only called from a synchronized method (unlockNames). My fix makes the other 2 methods that access queuedContexts synchronized, so there shouldn't be any other code-paths that modify queuedContexts in an unsafe manner. That being said, I haven't been able to reproduce the problem that I was originally trying to fix [1] reliably. My fix was done by code inspection.

If you have a way to reliably get the ConcurretnModificationException, could you try my fix to see if it fixes your instance of the issue?

https://issues.jenkins-ci.org/browse/JENKINS-42720

**Comment by stefanthurnherr** [comment]
Looks like a reasonable fix to me: this will ensure that all modifications of field `queuedContexts` happen from within a synchronized method, this should prevent ConcurrentModificationExceptions.

**Comment by adelcast** [comment]
FWIW, I have been running my pipeline with the fix for a week and haven't seen the issue. Before, I would hit it a couple of times a day.

**Comment by adelcast** [comment]
@abayer any chance you can help get this PR moving? anything else I need to do on my side? I believe the fix will solve at least 2 known issues, possibly more...

**Comment by amuniz** [comment]
I'd say this would require a more accurate fix, making those methods `synchronized` is _too much_ synchronization and could potentially lead to long waiting threads in a crowded Jenkins instance.

Would be better to use a `ReentrantLock` and play with read and write lock to reduce thread contention compared to the current proposal.

**Comment by dgeissl** [comment]
@amuniz if you are refering to http://lycog.com/concurency/performance-reentrantlock-synchronized/, this did not provide evidence that RetreeantLock is that much faster, as it was initialized for every run and so there was no concurrency at all.

**Comment by amuniz** [comment]
Not talking about efficiency but synchronizing on specific sections of the method body (not the entire method) and using the read lock when possible (which does not block any other reading thread as opposed to the current approach).

**Comment by dgeissl** [comment]
I see what you mean, but this seems like a big task, isn't it? What you propose is a overhaul of the plugins internal locking concept, while the PR just wants to fix the current bugged implementation.

Not saying that I the idea behind read-write-locks and narrowing down locked sections isn't great, it's just some other task beside fixing the current bug.

I've had so much trouble the last weeks with our build jobs that got migrated to jenkins pipeline just because the locking randomly got stuck. I even opened some tickets about them:
https://issues.jenkins-ci.org/browse/JENKINS-45506
https://issues.jenkins-ci.org/browse/JENKINS-44597
and there where more issues where I could not gather enough information to open a ticket for them.

After applying the this pull request most of our problems seem to be gone, even though I never expected them to be related. That means the current version has serious bugs that will be fixed with this pull request.

So please take into consideration to fix the urgent problem with a fast merge/release and queue the rewrite in another timeline.

**Comment by adelcast** [comment]
so this fix is following the pattern already present on LockableResourcesManager.java. As @dgeissl mentioned, using the ReentrantLock is a good idea, but then the whole file needs to be updated, which is a major architectural change. This fix is fixing what's currently broken using the approach already present in the plugin. 

Also, in this particular instance, the performance improvement would only apply to the loop that checks the context on each QueuedContext on queueContext (which would be a read lock)....which sounds like it shouldn't be a bit performance gain.

@amuniz any proposal on how can we move forward?

**Comment by adelcast** [comment]
@abayer @amuniz I am not sure how to proceed forward since this PR has been opened for almost 4 months....can we get the dialog going? I explained my rationale in favor of putting this change in, as did others. I do agree that the whole plugin would benefit from read/write locks, but that sounds like a pretty big architectural change. So, seems like we can either stay broken and start work on re-doing the plugin using read/write locks, or we could get this in, then work on the holistic re-architect. What I wouldn't want to happen is to start getting fragmentation as there is already several of us that are carrying this patch out-of-tree. Or if the decision is that this fix is not the way to go and will not be accepted, then I can plan to carry this out of tree until the holistic change goes in. Regardless, the community would benefit from getting to a resolution here.

**Comment by chrisgavin** [comment]
Please, please, please accept this fix. We've been suffering from this bug for months. Currently our only option is to use this fork. I appreciate the fix may not be perfect, but it's surely better than the status quo of the plugin being broken?

**Comment by amuniz** [comment]
Ok, I get you point here, it is a painful bug and this fixes it. Let's try to get it merged.
However I have a main concern that should be fixed (or probed to not be a problem): I've been bitten by synchronized methods calling `Descriptor.save()` and [jobConfigHistory](https://wiki.jenkins.io/display/JENKINS/JobConfigHistory+Plugin) installed. Every call to `Descriptor.save()` will trigger the config history listener that could potentially take long to finish, which will block any subsequent call to lock/unlock contexts.

I would require this to be fixed somehow before merging. I think @abayer has some ideas?

**Comment by abayer** [comment]
So the problem with `jobConfigHistory` is that it does a bunch of stuff every time `SaveableListener.fireOnChange` gets called, and that gets called in every `Descriptor.save()` call. A pretty simple brute-force way to get around that could be overriding `save()` in `LockableResourcesManager` to be the same as https://github.com/jenkinsci/jenkins/blob/7c16d8dc46ff1d0226ca674d1f16d5d252905df6/core/src/main/java/hudson/model/Descriptor.java#L869-L877 but without the `SaveableListener.fireOnChange` call.

**Comment by amuniz** [comment]
I'm ok with that as a short-term fix. Agree that using proper synchronization can be done later.

**Comment by adelcast** [comment]
ok, added overriden save to LockableResourceManager

**Comment by Wilfred** [comment]
This would be a huge help for us -- we're currently running a fork with this PR applied.

I've opened a [PR on jobConfigHistory](https://github.com/jenkinsci/jobConfigHistory-plugin/pull/65) because we were bitten by exactly the issue @amuniz described.

**Comment by adelcast** [comment]
@amuniz @abayer I added a stress test that spawn 50 threads that try to access the same lock, with random waits. I think the logic is correct, but I am seeing the following on the console out:

Sep 11, 2017 5:14:17 PM org.eclipse.jetty.server.AbstractConnector doStop
INFO: Stopped ServerConnector@12d2ce03{HTTP/1.1}{localhost:0}
Sep 11, 2017 5:14:17 PM org.eclipse.jetty.server.handler.ContextHandler doStop
INFO: Stopped o.e.j.w.WebAppContext@69f1a286{/jenkins,file:/home/adelcast/upstream/lockable-resources-plugin/target/jenkins-for-test/,UNAVAILABLE}{/home/adelcast/upstream/lockable-resources-plugin/target/jenkins-for-test}
WARN: The method class org.apache.commons.logging.impl.SLF4JLogFactory#release() was invoked.
WARN: Please see http://www.slf4j.org/codes.html#release for an explanation.

not sure if this is just a display issue or if there is something I need to add...

**Comment by abayer** [comment]
@adelcast That's just the test instance spinning down, nothing to worry about.

**Comment by adelcast** [comment]
I assume this failed since my test uses the decorator @WithPlugin("jobConfigHistory.hpi"), which requires that the hpi be placed under src/test/resources/plugins. We could either 

- Remove @WithPlugin for now, but we wouldn't be testing with the plugin that is known to cause issues
- Submit JobConfigHistory.hpi as source. This will work, but feels wrong to submit a binary to SCC
- Modify the build process to pull JobConfigHistoru.hpi to src/test/resources/plugins (don't know how to do that, but with some pointers I could implement it)

thoughts?

**Comment by amuniz** [comment]
I don't like to upload a plugin binary neither, but I think is the only way (as I like bullets 1 and 3 even less).
At any rate, it seems to be a [common practice](https://github.com/jenkinsci/jenkins/tree/08def67a18eee51de9f3f99bc2a792fee1c160e0/test/src/test/resources/plugins).

So +1 from me to upload it.

**Comment by abayer** [comment]
Could we just add a test dependency on jobConfigHistory?

**Comment by amuniz** [comment]
> Could we just add a test dependency on jobConfigHistory?

Not if we want the plugin installed *only* for that test (which I think it is what we want).

**Comment by adelcast** [comment]
@amuniz @abayer  ok, went ahead and updated the PR by adding  src/test/resources/plugins/JobConfigHistory.hpi. That made the CI happy.

**Comment by honnel** [comment]
same problem here, any plans for next release of lockable-resource-plugin?

**Comment by MarkSymsCtx** [comment]
I'm not sure if there is something else going on but have built a version of the plugin with the change it appears to deadlock when getting to the end of the lock (basically at the point where it would previously throw the concurrent modification exception.

**Comment by Constantin07** [comment]
experiencing the same issue, any plans to release the fix ?

**Comment by TobiX** [comment]
@Constantin07 This has been released in version 2.1 of the plugin (November 2017) - please report a new issue if you experience similar problems on more recent versions

**Pull request merged**
